name: fish_app
description: A new Fish Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  gal: ^2.3.0
  english_words: ^4.0.0
  provider: ^6.0.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  path: ^1.9.1
  font_awesome_flutter: ^10.8.0
  http: ^0.13.6
  crypto: ^3.0.3
  flutter_dotenv: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/photos/
